FROM eclipse-temurin:21-jdk-alpine

RUN addgroup basicgroup; adduser  --ingroup basicgroup --disabled-password alex
USER alex

WORKDIR /app
 
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
 
COPY src ./src
 
ENTRYPOINT ["./mvnw", "spring-boot:run"]